# Generated by Django 4.2.26 on 2025-11-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.CharField(max_length=100)),
                ('hospitalname', models.CharField(blank=True, max_length=200, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('mobileno', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(blank=True, max_length=200, null=True)),
                ('Prescription', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('DOCTORID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinapp.doctortable')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinapp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='doctortable',
            name='LOGINID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinapp.logintable'),
        ),
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinmentdate', models.DateField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('DOCTORID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinapp.doctortable')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinapp.usertable')),
            ],
        ),
    ]
