# Generated by Django 4.2.26 on 2025-11-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='Feedback',
            new_name='feedback',
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
