# Generated by Django 4.2.26 on 2025-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0002_rename_feedback_feedbacktable_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptiontable',
            name='patientname',
        ),
        migrations.AlterField(
            model_name='prescriptiontable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
