# Generated by Django 4.2.26 on 2025-11-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0003_remove_prescriptiontable_patientname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptiontable',
            name='DOCTORID',
        ),
        migrations.RemoveField(
            model_name='prescriptiontable',
            name='USERID',
        ),
        migrations.AddField(
            model_name='prescriptiontable',
            name='BookingID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skinapp.bookingtable'),
            preserve_default=False,
        ),
    ]
