# Generated by Django 4.2.26 on 2025-11-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0004_remove_prescriptiontable_doctorid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakingmedicineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(blank=True, max_length=200, null=True)),
                ('prescriptionimage', models.ImageField(blank=True, null=True, upload_to='intakingmedicine/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinapp.usertable')),
            ],
        ),
    ]
