# Generated by Django 4.2.26 on 2025-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0005_intakingmedicinetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
